config/routes.rb
MexPilotInstructor::Application.routes.draw do
  resources :group_records

  resources :groups

  resources :students

  resources :student_records

  match 'start' => "registration#start"
  match 'registration' => "registration#registration"
  post 'registration/save_registration' => "registration#save_registration"
  match 'stats' => "groups#choose_group"
  match 'group_stats' => 'groups#group_stats'
  match 'student_notes' => 'groups#student_notes'

end

app/models/group_record.rb
#begin
#CODE
#rescue
#  puts "Error #{$!}"
#  puts "#END#"
#end

class GroupRecord < ActiveRecord::Base
  attr_accessible :student_records, :group_id, :reg_date
  has_many :student_records
  has_many :students, :through => :student_records, :source => :group_student

  def self.get_group_students(group_id)
    self.where(:group_id => group_id).last.student_records
  end

  def self.get_group_student_stats(group_id)

    group = self.where(:group_id => group_id)

    #Pull out the student records for the corresponding group record
    gr = group.map{|c|c.student_records}

    #Remove empty brackets
    #Not necessary  if using group_by later on
    #gr.shift

    #Collect all arrays
    dd = []
    gr.each {|f|f.each { |d| dd<< d} }


    #Group each group records according to
    studhash = dd.group_by{|h| h.student_student_id}

    #Prepare hash-map for student stats
    studstats = {}

    #Iterate through each student and calculate the stats
    studhash.each do |student|
      #begin
      #Temporary
      preparation_array = []
      personal_attitude_array = []
      present_array = []

      #Create array of preparation
      student[1].each{|gg|
        preparation_array<< gg.preparation &&
            personal_attitude_array << gg.personalAttitude &&
            present_array << gg.present
      }

      student_name = {:name => Student.find(student[0]).name}

      #Calculate statistics
      preparation_avg =     {:preparation => preparation_array.sum / preparation_array.count}
      personal_attitude_avg = {:personal_attitude => personal_attitude_array.sum / personal_attitude_array.count}



      present_percentage = {:present => ((present_array.count(true).to_f/present_array.count).to_f*100.0).to_f }


      # merge hash
      hash_avg = {}
      hash_avg = hash_avg.merge(student_name)
      hash_avg = hash_avg.merge(preparation_avg)
      hash_avg = hash_avg.merge(personal_attitude_avg)
      hash_avg = hash_avg.merge(present_percentage)

      #Store stats for current student

      studstats[student[0]] = hash_avg

    end

    #Response will look like this
    # => {1=>{:preparation=>12, :personal_attitude=>6}, 2=>{:preparation=>18, :personal_attitude=>17}}

    return studstats
  end
end

app/controllers/group_records_controller.rb
class GroupRecordsController < ApplicationController
  # GET /group_records
  # GET /group_records.json
  def index
    @group_records = GroupRecord.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @group_records }
    end
  end

  # GET /group_records/1
  # GET /group_records/1.json
  def show
    @group_record = GroupRecord.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @group_record }
    end
  end

  # GET /group_records/new
  # GET /group_records/new.json
  def new
    @group_record = GroupRecord.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @group_record }
    end
  end

  # GET /group_records/1/edit
  def edit
    @group_record = GroupRecord.find(params[:id])
  end

  # POST /group_records
  # POST /group_records.json
  def create
    @group_record = GroupRecord.new(params[:group_record])

    respond_to do |format|
      if @group_record.save
        format.html { redirect_to @group_record, notice: 'Group record was successfully created.' }
        format.json { render json: @group_record, status: :created, location: @group_record }
      else
        format.html { render action: "new" }
        format.json { render json: @group_record.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /group_records/1
  # PUT /group_records/1.json
  def update
    @group_record = GroupRecord.find(params[:id])

    respond_to do |format|
      if @group_record.update_attributes(params[:group_record])
        format.html { redirect_to @group_record, notice: 'Group record was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @group_record.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /group_records/1
  # DELETE /group_records/1.json
  def destroy
    @group_record = GroupRecord.find(params[:id])
    @group_record.destroy

    respond_to do |format|
      format.html { redirect_to group_records_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/group_records_helper.rb
module GroupRecordsHelper
end

app/views/group_records/_form.html.erb
<%= form_for(@group_record) do |f| %>
  <% if @group_record.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@group_record.errors.count, "error") %> prohibited this group_record from being saved:</h2>

      <ul>
      <% @group_record.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/group_records/edit.html.erb
<h1>Editing group_record</h1>

<%= render 'form' %>

<%= link_to 'Show', @group_record %> |
<%= link_to 'Back', group_records_path %>

app/views/group_records/index.html.erb
<h1>Listing group_records</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @group_records.each do |group_record| %>
  <tr>
    <td><%= link_to 'Show', group_record %></td>
    <td><%= link_to 'Edit', edit_group_record_path(group_record) %></td>
    <td><%= link_to 'Destroy', group_record, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Group record', new_group_record_path %>

app/views/group_records/new.html.erb
<h1>New group_record</h1>

<%= render 'form' %>

<%= link_to 'Back', group_records_path %>

app/views/group_records/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_group_record_path(@group_record) %> |
<%= link_to 'Back', group_records_path %>