config/routes.rb
MexPilotInstructor::Application.routes.draw do
  resources :group_records

  resources :groups

  resources :students

  resources :student_records

  match 'start' => "registration#start"
  match 'registration' => "registration#registration"
  post 'registration/save_registration' => "registration#save_registration"
  match 'stats' => "groups#choose_group"
  match 'group_stats' => 'groups#group_stats'
  match 'student_notes' => 'groups#student_notes'

end

app/models/student_record.rb
class StudentRecord < ActiveRecord::Base
  attr_accessible :classDate, :note, :personalAttitude, :preparation, :present, :student_student_id
  has_one :group_student

  def name
    Student.find(student_student_id).name
  end

end

app/controllers/student_records_controller.rb
class StudentRecordsController < ApplicationController
  # GET /student_records
  # GET /student_records.json
  def index
    @student_records = StudentRecord.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @student_records }
    end
  end

  # GET /student_records/1
  # GET /student_records/1.json
  def show
    @student_record = StudentRecord.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @student_record }
    end
  end

  # GET /student_records/new
  # GET /student_records/new.json
  def new
    @student_record = StudentRecord.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @student_record }
    end
  end

  # GET /student_records/1/edit
  def edit
    @student_record = StudentRecord.find(params[:id])
  end

  # POST /student_records
  # POST /student_records.json
  def create
    @student_record = StudentRecord.new(params[:student_record])

    respond_to do |format|
      if @student_record.save
        format.html { redirect_to @student_record, notice: 'Student record was successfully created.' }
        format.json { render json: @student_record, status: :created, location: @student_record }
      else
        format.html { render action: "new" }
        format.json { render json: @student_record.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /student_records/1
  # PUT /student_records/1.json
  def update
    @student_record = StudentRecord.find(params[:id])

    respond_to do |format|
      if @student_record.update_attributes(params[:student_record])
        format.html { redirect_to @student_record, notice: 'Student record was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @student_record.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /student_records/1
  # DELETE /student_records/1.json
  def destroy
    @student_record = StudentRecord.find(params[:id])
    @student_record.destroy

    respond_to do |format|
      format.html { redirect_to student_records_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/student_records_helper.rb
module StudentRecordsHelper
end

app/views/student_records/_form.html.erb
<%= form_for(@student_record) do |f| %>
  <% if @student_record.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@student_record.errors.count, "error") %> prohibited this student_record from being saved:</h2>

      <ul>
      <% @student_record.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :present %><br />
    <%= f.check_box :present %>
  </div>
  <div class="field">
    <%= f.label :preparation %><br />
    <%= f.number_field :preparation %>
  </div>
  <div class="field">
    <%= f.label :personalAttitude %><br />
    <%= f.number_field :personalAttitude %>
  </div>
  <div class="field">
    <%= f.label :note %><br />
    <%= f.text_field :note %>
  </div>
  <div class="field">
    <%= f.label :student_student_id %><br />
    <%= f.number_field :student_student_id %>
  </div>
  <div class="field">
    <%= f.label :classDate %><br />
    <%= f.datetime_select :classDate %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/student_records/edit.html.erb
<h1>Editing student_record</h1>

<%= render 'form' %>

<%= link_to 'Show', @student_record %> |
<%= link_to 'Back', student_records_path %>

app/views/student_records/index.html.erb
<h1>Listing student_records</h1>

<table>
  <tr>
    <th>Present</th>
    <th>Preparation</th>
    <th>Personalattitude</th>
    <th>Note</th>
    <th>Student student</th>
    <th>Classdate</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @student_records.each do |student_record| %>
  <tr>
    <td><%= student_record.present %></td>
    <td><%= student_record.preparation %></td>
    <td><%= student_record.personalAttitude %></td>
    <td><%= student_record.note %></td>
    <td><%= student_record.student_student_id %></td>
    <td><%= student_record.classDate %></td>
    <td><%= link_to 'Show', student_record %></td>
    <td><%= link_to 'Edit', edit_student_record_path(student_record) %></td>
    <td><%= link_to 'Destroy', student_record, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Student record', new_student_record_path %>

app/views/student_records/new.html.erb
<h1>New student_record</h1>

<%= render 'form' %>

<%= link_to 'Back', student_records_path %>

app/views/student_records/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Present:</b>
  <%= @student_record.present %>
</p>

<p>
  <b>Preparation:</b>
  <%= @student_record.preparation %>
</p>

<p>
  <b>Personalattitude:</b>
  <%= @student_record.personalAttitude %>
</p>

<p>
  <b>Note:</b>
  <%= @student_record.note %>
</p>

<p>
  <b>Student student:</b>
  <%= @student_record.student_student_id %>
</p>

<p>
  <b>Classdate:</b>
  <%= @student_record.classDate %>
</p>


<%= link_to 'Edit', edit_student_record_path(@student_record) %> |
<%= link_to 'Back', student_records_path %>